
package br.ulbra.view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author S.lucas
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     */
    public FrMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jSerie = new javax.swing.JMenuItem();
        jUsuarios = new javax.swing.JMenuItem();
        jSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jR1 = new javax.swing.JMenuItem();
        jR2 = new javax.swing.JMenuItem();
        re3 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 54, 122));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/c1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 100, 310, 220);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Evening Sunshine.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 410);

        jMenuBar1.setBackground(new java.awt.Color(164, 164, 235));

        jMenu1.setText("CADASTRO");

        jSerie.setText("Séries");
        jSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSerieActionPerformed(evt);
            }
        });
        jMenu1.add(jSerie);

        jUsuarios.setText("Contas");
        jUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUsuariosActionPerformed(evt);
            }
        });
        jMenu1.add(jUsuarios);

        jSair.setText("Sair");
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jMenu1.add(jSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("RELATÓRIOS");

        jR1.setText("R1");
        jR1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR1ActionPerformed(evt);
            }
        });
        jMenu2.add(jR1);

        jR2.setText("R2");
        jR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jR2ActionPerformed(evt);
            }
        });
        jMenu2.add(jR2);

        re3.setText("R3");
        re3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                re3ActionPerformed(evt);
            }
        });
        jMenu2.add(re3);

        jMenuItem3.setText("R4");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUsuariosActionPerformed
        try {
            new FrUsuario().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUsuariosActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jSairActionPerformed

    private void jSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSerieActionPerformed
        try {
            new FrSerie().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jSerieActionPerformed
    public void showRel() throws SQLException, JRException {
        Connection con = null;
        try {
//Criando o driver de conexão onde diz bdAulaPOOII deve ser substituída
//pelo banco de vocês
            con
                    = DriverManager.getConnection("jdbc:mysql://localhost:3306/serie", "root", "");
//objeto responsável por exibir o relatório. Observe que o arquivo .jasper
//deve estar em uma pasta da unidade C: ex.: Relatorio
            JasperPrint print = JasperFillManager.fillReport("C:\\relatorio\\rel.jasper", null, con);
            JasperViewer.viewReport(print, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE,
                    null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        } finally {
            con.close();
        }
    }
    private void jR1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR1ActionPerformed
        try {
            showRel();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jR1ActionPerformed

    private void jR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jR2ActionPerformed
        try {
            showRe2();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void showRe2() throws SQLException, JRException {
        Connection con = null;
        try {
//Criando o driver de conexão onde diz bdAulaPOOII deve ser substituída
//pelo banco de vocês
            con
                    = DriverManager.getConnection("jdbc:mysql://localhost:3306/serie", "root", "");
//objeto responsável por exibir o relatório. Observe que o arquivo .jasper
//deve estar em uma pasta da unidade C: ex.: Relatorio
            JasperPrint print = JasperFillManager.fillReport("C:\\relatorio\\REL2.jasper", null, con);
            JasperViewer.viewReport(print, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE,
                    null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        } finally {
            con.close();
        }


    }//GEN-LAST:event_jR2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
      

   
    }//GEN-LAST:event_jMenuItem3ActionPerformed
 public void showRe3() throws SQLException, JRException {
        Connection con = null;
        try {
//Criando o driver de conexão onde diz bdAulaPOOII deve ser substituída
//pelo banco de vocês
            con
                    = DriverManager.getConnection("jdbc:mysql://localhost:3306/serie", "root", "");
//objeto responsável por exibir o relatório. Observe que o arquivo .jasper
//deve estar em uma pasta da unidade C: ex.: Relatorio
            JasperPrint print = JasperFillManager.fillReport("C:\\relatorio\\rel3.jasper", null, con);
            JasperViewer.viewReport(print, false);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE,
                    null, ex);
            JOptionPane.showMessageDialog(rootPane, ex);
        } finally {
            con.close();
        }

 }
        
    private void re3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_re3ActionPerformed
        try {
            showRe3();
        } catch (SQLException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_re3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jR1;
    private javax.swing.JMenuItem jR2;
    private javax.swing.JMenuItem jSair;
    private javax.swing.JMenuItem jSerie;
    private javax.swing.JMenuItem jUsuarios;
    private javax.swing.JMenuItem re3;
    // End of variables declaration//GEN-END:variables
}
