/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.DAO.UsuarioDAO;
import br.ulbra.entity.Usuario;
import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author S.lucas
 */
public class FrUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrUsuario
     */
    public FrUsuario() throws SQLException {
        initComponents();
        setLocationRelativeTo(null); // centralizar
        controlarBtn(1);
        edCod.setEnabled(false);
        readJTable();

    }
    Connection con;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbUsuario = new javax.swing.JTable();
        pnCad = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        edCod = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        edEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edNome = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        edSenha1 = new javax.swing.JPasswordField();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edSenha2 = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        fone = new javax.swing.JLabel();
        edFone = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        edCep = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        edRua = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        edBairro = new javax.swing.JTextField();
        btAlterar = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        edCidade = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        j11 = new javax.swing.JLabel();
        btExcluir = new javax.swing.JButton();
        edEstado = new javax.swing.JTextField();
        edNumero = new javax.swing.JTextField();
        j10 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edPesquisa = new javax.swing.JTextField();
        cbTipo = new javax.swing.JComboBox<>();
        btPesquisar = new javax.swing.JButton();
        btNovo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Evening Sunshine.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        tbUsuario.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Fone", "Senha", "E-mail", "Cep", "Rua", "Bairro", "Cidade", "Estado", "Número"
            }
        ));
        tbUsuario.setGridColor(new java.awt.Color(255, 255, 255));
        tbUsuario.setOpaque(false);
        tbUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbUsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbUsuario);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(300, 290, 620, 90);

        pnCad.setBackground(new java.awt.Color(54, 33, 89));
        pnCad.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/home.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnCad.add(jLabel4);
        jLabel4.setBounds(20, 40, 20, 20);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home usuário");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnCad.add(jLabel5);
        jLabel5.setBounds(40, 40, 100, 20);
        pnCad.add(jSeparator1);
        jSeparator1.setBounds(20, 70, 50, 10);
        pnCad.add(jSeparator2);
        jSeparator2.setBounds(20, 70, 50, 10);
        pnCad.add(jSeparator3);
        jSeparator3.setBounds(20, 70, 160, 10);

        jPanel3.setBackground(new java.awt.Color(86, 86, 118));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Código");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        edCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edCod, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(edCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnCad.add(jPanel3);
        jPanel3.setBounds(0, 150, 290, 50);

        jPanel4.setBackground(new java.awt.Color(48, 44, 78));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 24, 22));

        edEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edEmailActionPerformed(evt);
            }
        });
        jPanel4.add(edEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 50, -1));
        jPanel4.add(edNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 100, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 24, 22));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("E-mail");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 24, 22));

        j4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j4.setForeground(new java.awt.Color(255, 255, 255));
        j4.setText("Senha");
        j4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));
        jPanel4.add(edSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 100, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 24, 22));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Confirmar senha");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        edSenha2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edSenha2ActionPerformed(evt);
            }
        });
        jPanel4.add(edSenha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 110, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 24, 22));

        fone.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fone.setForeground(new java.awt.Color(255, 255, 255));
        fone.setText("Fone");
        jPanel4.add(fone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 36, -1));

        edFone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edFoneActionPerformed(evt);
            }
        });
        jPanel4.add(edFone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 100, -1));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 24, 22));

        j7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j7.setForeground(new java.awt.Color(255, 255, 255));
        j7.setText("Cep");
        j7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 30, -1));

        edCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCepActionPerformed(evt);
            }
        });
        edCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                edCepKeyReleased(evt);
            }
        });
        jPanel4.add(edCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 100, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 24, 22));

        j8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j8.setForeground(new java.awt.Color(255, 255, 255));
        j8.setText("Rua");
        j8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 30, -1));

        edRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edRuaActionPerformed(evt);
            }
        });
        jPanel4.add(edRua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 24, 22));

        j9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j9.setForeground(new java.awt.Color(255, 255, 255));
        j9.setText("Bairro");
        j9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 50, -1));

        edBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edBairroActionPerformed(evt);
            }
        });
        jPanel4.add(edBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 100, -1));

        btAlterar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btAlterar.setText("Alterar");
        btAlterar.setBorder(null);
        btAlterar.setOpaque(false);
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });
        jPanel4.add(btAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 50, 30));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 24, 22));

        j3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j3.setForeground(new java.awt.Color(255, 255, 255));
        j3.setText("Cidade");
        j3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 50, -1));

        edCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edCidadeActionPerformed(evt);
            }
        });
        jPanel4.add(edCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 100, -1));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 24, 22));

        j11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j11.setForeground(new java.awt.Color(255, 255, 255));
        j11.setText("Estado");
        j11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 70, -1));

        btExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setBorder(null);
        btExcluir.setOpaque(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        jPanel4.add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 60, 30));

        edEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edEstadoActionPerformed(evt);
            }
        });
        jPanel4.add(edEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, -1));

        edNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNumeroActionPerformed(evt);
            }
        });
        jPanel4.add(edNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 100, -1));

        j10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        j10.setForeground(new java.awt.Color(255, 255, 255));
        j10.setText("Número");
        j10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel4.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 70, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mais.png"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 24, 22));

        btSalvar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btSalvar.setText("Salvar");
        btSalvar.setBorder(null);
        btSalvar.setOpaque(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        jPanel4.add(btSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 50, 30));

        pnCad.add(jPanel4);
        jPanel4.setBounds(0, 200, 290, 450);

        jPanel1.add(pnCad);
        pnCad.setBounds(0, 0, 290, 680);

        jPanel2.setBackground(new java.awt.Color(84, 52, 104));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Menu/Usuario/");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suas credenciais...");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pesquisar:");

        edPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisaActionPerformed(evt);
            }
        });

        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "E-mail", "Fone" }));
        cbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoActionPerformed(evt);
            }
        });

        btPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        btPesquisar.setBorder(null);
        btPesquisar.setOpaque(false);
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        btNovo.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btNovo.setText("Novo");
        btNovo.setBorder(null);
        btNovo.setOpaque(false);
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel10)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(14, 14, 14))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(290, 90, 650, 180);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pesquisar:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(38, 53, 68, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 935, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPesquisaActionPerformed

    public void readJTableForDesc(String nome, String tipo) throws SQLException {
        DefaultTableModel modelo
                = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO pdao = new UsuarioDAO();
        for (Usuario p : pdao.readForDesc(nome, tipo)) {
            modelo.addRow(new Object[]{
                p.getIdNome(),
                p.getNome(),
                p.getFone(),
                p.getSenha(),
                p.getEmail(),
                p.getCep(),
                p.getRua(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero(),});
        }
    }

    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbUsuario.getModel();
        modelo.setNumRows(0);
        UsuarioDAO udao = new UsuarioDAO();
        for (Usuario p : udao.read()) {
            modelo.addRow(new Object[]{
                p.getIdNome(),
                p.getNome(),
                p.getFone(),
                p.getSenha(),
                p.getEmail(),
                p.getCep(),
                p.getRua(),
                p.getBairro(),
                p.getCidade(),
                p.getEstado(),
                p.getNumero(),});
        }
    }

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        controlarBtn(1);
        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que você deseja excluir este registro?",
                    "Excluir Registro", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                u.setIdNome(Integer.parseInt(edCod.getText()));

                ud.delete(u);
                readJTable();
                controlarBtn(1);
            } else {
                JOptionPane.showMessageDialog(null, "Exclusão Cancelada com sucesso!!");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
        }

    }//GEN-LAST:event_btExcluirActionPerformed

    private void edCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCodActionPerformed

    private void edBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edBairroActionPerformed

    public void controlarBtn(int op) {
        switch (op) {
            case 1:
                pnCad.setVisible(false);
                break;
            case 2:
                pnCad.setVisible(true);
                btAlterar.setEnabled(false);
                btSalvar.setEnabled(true);
                btExcluir.setEnabled(false);
                break;
            case 3:
                pnCad.setVisible(true);
                btAlterar.setEnabled(true);
                btSalvar.setEnabled(false);
                btExcluir.setEnabled(true);
                break;

        }
        this.pack();
    }

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        try {
            String tipo = null;
            switch (cbTipo.getSelectedIndex()) {
                case 0:
                    tipo = "nome";
                    break;
                case 1:
                    tipo = "email";
                    break;
                case 2:
                    tipo = "fone";
                    break;
                default:
                    tipo = "nome";
            }
            readJTableForDesc(edPesquisa.getText(), tipo);
        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        controlarBtn(2);
    }//GEN-LAST:event_btNovoActionPerformed

    private void tbUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbUsuarioMouseClicked
        controlarBtn(3);
        if (tbUsuario.getSelectedRow() != -1) {
            edCod.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 0).toString());
            edNome.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 1).toString());
            edEmail.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 2).toString());
            edSenha1.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 3).toString());
            edSenha2.setText(edSenha1.getText());
            edFone.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 4).toString());
            edCep.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 5).toString());
            edRua.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 6).toString());
            edBairro.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 7).toString());
            edCidade.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 8).toString());
            edEstado.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 9).toString());
            edNumero.setText(tbUsuario.getValueAt(tbUsuario.getSelectedRow(), 10).toString());
        }

    }//GEN-LAST:event_tbUsuarioMouseClicked

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        controlarBtn(1);
        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();

            u.setNome(edNome.getText());
            u.setEmail(edEmail.getText());
            u.setSenha(edSenha1.getText());
            u.setFone(edFone.getText());
            u.setCep(edCep.getText());
            u.setRua(edRua.getText());
            u.setBairro(edBairro.getText());
            u.setCidade(edCidade.getText());
            u.setEstado(edEstado.getText());
            u.setNumero(Integer.parseInt(edNumero.getText()));

            if (edSenha1.getText().equals(edSenha2.getText())) {
                u.setIdNome(Integer.parseInt(edCod.getText()));
                ud.update(u);
                readJTable();
                controlarBtn(1);
            } else {
                JOptionPane.showMessageDialog(null,
                        "Você inseriu senhas diferentes!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro:" + e.getMessage());
        }

    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        Usuario u = new Usuario();
        try {
            UsuarioDAO ud = new UsuarioDAO();

            u.setEmail(edEmail.getText());
            u.setNome(edNome.getText());
            u.setFone(edFone.getText());
            u.setSenha(edSenha1.getText());
            u.setCep(edCep.getText());
            u.setRua(edRua.getText());
            u.setBairro(edBairro.getText());
            u.setCidade(edCidade.getText());
            u.setEstado(edEstado.getText());
            u.setNumero(Integer.parseInt(edNumero.getText()));

            if (edSenha1.getText().equals(edSenha2.getText())) {
                ud.create(u);
                readJTable();
            } else {
                JOptionPane.showMessageDialog(null, "Você inseriu senhas diferentes!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btSalvarActionPerformed

    private void edFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edFoneActionPerformed

    private void edCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCepActionPerformed

    private void edRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edRuaActionPerformed

    private void edNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edNumeroActionPerformed

    private void edCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edCidadeActionPerformed

    private void edEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edEstadoActionPerformed

    private void edCepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edCepKeyReleased
        edRua.setText("Aguarde...");
        if (edCep.getText().length() == 8) {
            buscarCep(edCep.getText());
        }
    }//GEN-LAST:event_edCepKeyReleased

    private void edEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edEmailActionPerformed

    private void cbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoActionPerformed

    private void edSenha2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edSenha2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edSenha2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrUsuario().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrUsuario.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    public void buscarCep(String cep) {
        String json;
        try {
            URL url = new URL("http://viacep.com.br/ws/" + cep + "/json");
            URLConnection urlConnection = url.openConnection();
            InputStream is = urlConnection.getInputStream();
            BufferedReader br = new BufferedReader(new InputStreamReader(is));
            StringBuilder jsonSb = new StringBuilder();
            br.lines().forEach(l -> jsonSb.append(l.trim()));
            json = jsonSb.toString();
            //JOptionPane.showMessageDialog(null, json);
            json = json.replaceAll("[{},:]", "");
            json = json.replaceAll("\"", "\n");
            String array[] = new String[30];
            array = json.split("\n");
            // JOptionPane.showMessageDialog(null, array);
            String logradouro = array[7];
            String bairro = array[15];
            String cidade = array[19];
            String uf = array[23];
            edRua.setText(logradouro);
            edBairro.setText(bairro);
            edCidade.setText(cidade);
            edEstado.setText(uf);
            //JOptionPane.showMessageDialog(null, logradouro + "" + bairro + "" + cidade + "" + uf);
        } catch (Exception e) {
//throw new RuntimeException(e);
            JOptionPane.showMessageDialog(null, "Erro:" + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JTextField edBairro;
    private javax.swing.JTextField edCep;
    private javax.swing.JTextField edCidade;
    private javax.swing.JTextField edCod;
    private javax.swing.JTextField edEmail;
    private javax.swing.JTextField edEstado;
    private javax.swing.JTextField edFone;
    private javax.swing.JTextField edNome;
    private javax.swing.JTextField edNumero;
    private javax.swing.JTextField edPesquisa;
    private javax.swing.JTextField edRua;
    private javax.swing.JPasswordField edSenha1;
    private javax.swing.JPasswordField edSenha2;
    private javax.swing.JLabel fone;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel pnCad;
    private javax.swing.JTable tbUsuario;
    // End of variables declaration//GEN-END:variables
}
